### ISSUE TITLE
Notepad++ crashes when using image from invalid internet source

### ISSUE THREAD

**Issue by havlisimo** [nea/MarkdownViewerPlusPlus#92]
## Issue description
Notepad++ crashes when I add image as a link which requires authentication . In my case I am trying to add GitLab pipeline status for a private repository on our local server.

### Markdown to reproduce
```
[![pipeline status](https://git.my-company.cz/git/project-name/badges/dev/pipeline.svg)](https://git.my-company.cz/git/project-name/commits/dev)
```

### Exceptions
When using valid url which requires authentication:
```
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   v System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   v System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   v System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
```
When using invalid url
```
System.Net.WebException: Remote host cannot be found: 'git.my-company.cz'
   v System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   v System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   v System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
```

### Environment
* Notepad++ _7.5.8 (x86)_
* MarkdownViewer++ _0.8.2.0 (0.8.2.25525)_
* Windows _10 (x64)_

**Comment by nea** [comment]
Hi @havlisimo 

There is no common syntax to add credentials to an image link other than having the credentials in the URL. If that is not possible for your case I don't see any workaround.

Regarding the invalid url, yeah, that should be caught.


Sorry

**Comment by sanchor** [comment]
i've encountered the same problem, i assume, with the following error (503) message:

> System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

**Comment by ffonz** [comment]
Because of security reasons, I don't have an internet connection on my machine. When opening the README.md attached in the MarkdownViewerPlusPlus-0.8.2-x64.zip, I get the following exception (because of trying to read the image from the internet?):

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
> System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 138.91.141.243:443
>    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

I assume it is the same issue as described before. Could this issue get a high priority?

**Comment by hgdagon** [comment]
I'll just bump this 'cause I have the same issue even with local files (that do exist).

**Comment by Neustradamus** [comment]
@nea: I confirm this problem with current Notepad++ x86 and x64 version: 8.7.5.

Can you solve it?

Note: I have no problem with this other plugin:
- https://github.com/mohzy83/NppMarkdownPanel

Thanks in advance.
